### ISSUE TITLE
[Node importer] - Errors

### ISSUE THREAD

**Issue by esnesi** [scottadkin/node-utstats-2#1]
Getting these on the Node Importer

![image](https://user-images.githubusercontent.com/58574380/133682803-cc75108c-71df-4d81-a674-da29d0bbfc19.png)

**Comment by esnesi** [comment]
renamed 1 logfile without the U capital.
After that it did started to seem importing a logfile with a capital, but crashed on that one.
![image](https://user-images.githubusercontent.com/58574380/133683245-089d9400-0876-4155-a7e6-b54a4e68d7c1.png)

**Comment by scottadkin** [comment]
Looks like I forgot to make the prefix case insensitive, will fix it when I'm at my pc.

**Comment by scottadkin** [comment]
I've updated the repo with case insensitive checking for log prefixes and extensions, give it a try and see if it's fixed the problem.

**Comment by esnesi** [comment]
Sadly same issue is persisting (services restarted)

"unreal.ngLog.2021.08.01.00.07.05.5555.log does not have the prefix unreal.ngLog.."

Changing the "logFilePrefix" variable does not seem to affect this.

**Comment by scottadkin** [comment]
I somehow forgot to actually apply tolowercase, should work this time unless I'm braindead again.

**Comment by esnesi** [comment]
[23:21:31] Pass: Found 270 log files to import.
[23:21:31] Progress: Starting import of log number 1 of 270
[23:21:31] Notice: Starting import of log file Unreal.ngLog.2021.08.01.00.07.05.                         5555.log
[23:21:31] Notice: Log file id is 3
[23:21:31] Notice: Gametype is Last Man Standing
[23:21:31] Pass: Inserted gametype info into database.
[23:21:31] Notice: Gametype is Last Man Standing
[23:21:31] Pass: Inserted server info into database.
[23:21:31] Pass: Inserted map info into database.
[23:21:31] Pass: Inserted match info into database.
[23:21:31] Error: Problem setting player id Error: ER_TRUNCATED_WRONG_VALUE_FOR_                         FIELD: Incorrect integer value: '' for column `node_utstats2`.`nstats_player_tot                         als`.`face` at row 1
[23:21:31] Pass: There are no duplicates to import
[23:21:31] Notice: (LMS) Match join cutoff point is 132.73
[23:21:31] Pass: Last man standing stats update complete.
[23:21:31] Notice: Starting face stats update
[23:21:31] Notice: A face with the name soldierskins.blkt5malcom does not exist,                          creating one now.
[23:21:31] Pass: The face soldierskins.blkt5malcom was inserted with the id of 1
[23:21:31] Notice: A face with the name undefined does not exist, creating one n                         ow.
[23:21:31] Pass: The face undefined was inserted with the id of 2
[23:21:31] Notice: A face with the name soldierskins.sldr5brock does not exist,                          creating one now.
[23:21:31] Pass: The face soldierskins.sldr5brock was inserted with the id of 3
[23:21:31] Notice: A face with the name soldierskins.hkil5vector does not exist,                          creating one now.
[23:21:31] Pass: The face soldierskins.hkil5vector was inserted with the id of 4
[23:21:31] Notice: A face with the name commandoskins.daco5luthor does not exist                         , creating one now.
[23:21:31] Pass: The face commandoskins.daco5luthor was inserted with the id of                          5
[23:21:31] Pass: Updated face stats in database.
[23:21:31] Notice: There is no data for the voice "botpack.voicemaletwo", creati                         ng now.
[23:21:31] Notice: There is no data for the voice "botpack.voicemaleone", creati                         ng now.
[23:21:31] Warning: Failed to update player voice
[23:21:31] Warning: Failed to update player voice
[23:21:31] Pass: Updated player frag performance.
[23:21:31] Pass: Updated player winstats performance.
[23:21:31] Notice: Starting to insert player ping data.
Trace: PingManager.insertPingData() Error: ER_BAD_NULL_ERROR: Column 'player' ca                         nnot be null error
    at PingManager.insertPingData (/home/esnesi/unreal/_NUTStats2/api/importer/p                         ingmanager.js:115:21)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async MatchManager.import (/home/esnesi/unreal/_NUTStats2/api/importer/ma                         tchmanager.js:195:13)
    at async Importer.importLogs (/home/esnesi/unreal/_NUTStats2/api/importer/im                         porter.js:74:37)
    at async MyEmitter.<anonymous> (/home/esnesi/unreal/_NUTStats2/api/importer/                         importer.js:119:17)
Trace: Error: ER_BAD_NULL_ERROR: Column 'player_id' cannot be null
    at Query.Sequence._packetToError (/home/esnesi/unreal/_NUTStats2/node_module                         s/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/home/esnesi/unreal/_NUTStats2/node_modules/mysql/lib/                         protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/home/esnesi/unreal/_NUTStats2/node_modules/mysql/                         lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/esnesi/unreal/_NUTStats2/node_modules/mysql/li                         b/protocol/Parser.js:433:10)
    at Parser.write (/home/esnesi/unreal/_NUTStats2/node_modules/mysql/lib/proto                         col/Parser.js:43:10)
    at Protocol.write (/home/esnesi/unreal/_NUTStats2/node_modules/mysql/lib/pro                         tocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/esnesi/unreal/_NUTStats2/node_modules/mysql/lib                         /Connection.js:88:28)
    at Socket.<anonymous> (/home/esnesi/unreal/_NUTStats2/node_modules/mysql/lib                         /Connection.js:526:10)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:290:12)
    --------------------
    at Pool.query (/home/esnesi/unreal/_NUTStats2/node_modules/mysql/lib/Pool.js                         :199:23)
    at /home/esnesi/unreal/_NUTStats2/api/player.js:319:19
    at tryCallTwo (/home/esnesi/unreal/_NUTStats2/node_modules/promise/lib/core.                         js:45:5)
    at doResolve (/home/esnesi/unreal/_NUTStats2/node_modules/promise/lib/core.j                         s:200:13)
    at new Promise (/home/esnesi/unreal/_NUTStats2/node_modules/promise/lib/core                         .js:66:3)
    at Player.insertMatchData (/home/esnesi/unreal/_NUTStats2/api/player.js:252:                         16)
    at PlayerManager.insertMatchData (/home/esnesi/unreal/_NUTStats2/api/importe                         r/playermanager.js:1298:46)
    at MatchManager.import (/home/esnesi/unreal/_NUTStats2/api/importer/matchman                         ager.js:198:38)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Importer.importLogs (/home/esnesi/unreal/_NUTStats2/api/importer/im                         porter.js:74:37) {
  code: 'ER_BAD_NULL_ERROR',
  errno: 1048,
  sqlMessage: "Column 'player_id' cannot be null",
  sqlState: '23000',
  index: 0,
  sql: "INSERT INTO nstats_player_matches VALUES(NULL,3,1627776425,1,NULL,false,                         false,true,'176.78.129.25','pt',1,1,1,true,false,387.84729,0,1,23,2,25,11,2,0,0,                         69.44444444444444,\n" +
    '                0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,4,\n' +
    '                0,\n' +
    '                0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,\n' +
    "                0,0,52,105,245,'-633.33',217.415604,748.7318219200001,1457.                         710449,25,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0)"
}
    at Query.<anonymous> (/home/esnesi/unreal/_NUTStats2/api/player.js:322:29)
    at Query.<anonymous> (/home/esnesi/unreal/_NUTStats2/node_modules/mysql/lib/                         Connection.js:526:10)
    at Query._callback (/home/esnesi/unreal/_NUTStats2/node_modules/mysql/lib/Co                         nnection.js:488:16)
    at Query.Sequence.end (/home/esnesi/unreal/_NUTStats2/node_modules/mysql/lib                         /protocol/sequences/Sequence.js:83:24)
    at Query.ErrorPacket (/home/esnesi/unreal/_NUTStats2/node_modules/mysql/lib/                         protocol/sequences/Query.js:92:8)
    at Protocol._parsePacket (/home/esnesi/unreal/_NUTStats2/node_modules/mysql/                         lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/esnesi/unreal/_NUTStats2/node_modules/mysql/li                         b/protocol/Parser.js:433:10)
    at Parser.write (/home/esnesi/unreal/_NUTStats2/node_modules/mysql/lib/proto                         col/Parser.js:43:10)
    at Protocol.write (/home/esnesi/unreal/_NUTStats2/node_modules/mysql/lib/pro                         tocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/esnesi/unreal/_NUTStats2/node_modules/mysql/lib                         /Connection.js:88:28)
/home/esnesi/unreal/_NUTStats2/node_modules/mysql/lib/protocol/Parser.js:437
      throw err; // Rethrow non-MySQL errors

**Comment by scottadkin** [comment]
Yeah I need to sort that stuff out, guessing you are using Linux?

**Comment by esnesi** [comment]
Linux host, correct.

**Comment by scottadkin** [comment]
I fixed a lot of crashes while running on linux, see how it goes now.

**Comment by esnesi** [comment]
[10:24:06] Progress: Starting import of log number 1 of 270
[10:24:06] Notice: Starting import of log file Unreal.ngLog.2021.08.01.00.07.05.                                                                                                                                                             5555.log
[10:24:06] Notice: Log file id is 5
[10:24:06] Notice: Gametype is Last Man Standing
[10:24:06] Pass: Inserted gametype info into database.
[10:24:06] Notice: Gametype is Last Man Standing
[10:24:06] Pass: Inserted server info into database.
[10:24:07] Pass: Inserted map info into database.
[10:24:07] Pass: Inserted match info into database.
[10:24:07] Error: Problem setting player id Error: ER_TRUNCATED_WRONG_VALUE_FOR_                                                                                                                                                             FIELD: Incorrect integer value: '' for column `node_utstats2`.`nstats_player_tot                                                                                                                                                             als`.`face` at row 1
[10:24:07] Pass: There are no duplicates to import
[10:24:07] Notice: (LMS) Match join cutoff point is 132.73
[10:24:07] Pass: Last man standing stats update complete.
[10:24:07] Notice: Starting face stats update
[10:24:07] Pass: Updated face stats in database.
[10:24:07] Notice: Updating voice stats for "botpack.voicemaletwo".
[10:24:07] Notice: Updating voice stats for "botpack.voicemaleone".
[10:24:07] Warning: Failed to update player voice
[10:24:07] Warning: Failed to update player voice
[10:24:07] Pass: Updated player frag performance.
[10:24:07] Pass: Updated player winstats performance.
[10:24:07] Notice: Starting to insert player ping data.
Trace: PingManager.insertPingData() Error: ER_BAD_NULL_ERROR: Column 'player' ca                                                                                                                                                             nnot be null error
    at PingManager.insertPingData (/home/esnesi/unreal/_NUTStats2/api/importer/p                                                                                                                                                             ingmanager.js:115:21)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async MatchManager.import (/home/esnesi/unreal/_NUTStats2/api/importer/ma                                                                                                                                                             tchmanager.js:195:13)
    at async Importer.importLogs (/home/esnesi/unreal/_NUTStats2/api/importer/im                                                                                                                                                             porter.js:74:37)
    at async MyEmitter.<anonymous> (/home/esnesi/unreal/_NUTStats2/api/importer/                                                                                                                                                             importer.js:119:17)
Trace: Error: ER_BAD_NULL_ERROR: Column 'player_id' cannot be null
    at Query.Sequence._packetToError (/home/esnesi/unreal/_NUTStats2/node_module                                                                                                                                                             s/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/home/esnesi/unreal/_NUTStats2/node_modules/mysql/lib/                                                                                                                                                             protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/home/esnesi/unreal/_NUTStats2/node_modules/mysql/                                                                                                                                                             lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/esnesi/unreal/_NUTStats2/node_modules/mysql/li                                                                                                                                                             b/protocol/Parser.js:433:10)
    at Parser.write (/home/esnesi/unreal/_NUTStats2/node_modules/mysql/lib/proto                                                                                                                                                             col/Parser.js:43:10)
    at Protocol.write (/home/esnesi/unreal/_NUTStats2/node_modules/mysql/lib/pro                                                                                                                                                             tocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/esnesi/unreal/_NUTStats2/node_modules/mysql/lib                                                                                                                                                             /Connection.js:88:28)
    at Socket.<anonymous> (/home/esnesi/unreal/_NUTStats2/node_modules/mysql/lib                                                                                                                                                             /Connection.js:526:10)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:290:12)
    --------------------
    at Pool.query (/home/esnesi/unreal/_NUTStats2/node_modules/mysql/lib/Pool.js                                                                                                                                                             :199:23)
    at /home/esnesi/unreal/_NUTStats2/api/player.js:319:19
    at tryCallTwo (/home/esnesi/unreal/_NUTStats2/node_modules/promise/lib/core.                                                                                                                                                             js:45:5)
    at doResolve (/home/esnesi/unreal/_NUTStats2/node_modules/promise/lib/core.j                                                                                                                                                             s:200:13)
    at new Promise (/home/esnesi/unreal/_NUTStats2/node_modules/promise/lib/core                                                                                                                                                             .js:66:3)
    at Player.insertMatchData (/home/esnesi/unreal/_NUTStats2/api/player.js:252:                                                                                                                                                             16)
    at PlayerManager.insertMatchData (/home/esnesi/unreal/_NUTStats2/api/importe                                                                                                                                                             r/playermanager.js:1298:46)
    at MatchManager.import (/home/esnesi/unreal/_NUTStats2/api/importer/matchman                                                                                                                                                             ager.js:198:38)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Importer.importLogs (/home/esnesi/unreal/_NUTStats2/api/importer/im                                                                                                                                                             porter.js:74:37) {
  code: 'ER_BAD_NULL_ERROR',
  errno: 1048,
  sqlMessage: "Column 'player_id' cannot be null",
  sqlState: '23000',
  index: 0,
  sql: "INSERT INTO nstats_player_matches VALUES(NULL,5,1627776425,1,NULL,false,                                                                                                                                                             false,true,'176.78.129.25','pt',1,1,1,true,false,387.84729,0,1,23,2,25,11,2,0,0,                                                                                                                                                             69.44444444444444,\n" +
    '                0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,4,\n' +
    '                0,\n' +
    '                0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,\n' +
    "                0,0,52,105,245,'-633.33',217.415604,748.7318219200001,1457.                                                                                                                                                             710449,25,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0)"
}
    at Query.<anonymous> (/home/esnesi/unreal/_NUTStats2/api/player.js:322:29)
    at Query.<anonymous> (/home/esnesi/unreal/_NUTStats2/node_modules/mysql/lib/                                                                                                                                                             Connection.js:526:10)
    at Query._callback (/home/esnesi/unreal/_NUTStats2/node_modules/mysql/lib/Co                                                                                                                                                             nnection.js:488:16)
    at Query.Sequence.end (/home/esnesi/unreal/_NUTStats2/node_modules/mysql/lib                                                                                                                                                             /protocol/sequences/Sequence.js:83:24)
    at Query.ErrorPacket (/home/esnesi/unreal/_NUTStats2/node_modules/mysql/lib/                                                                                                                                                             protocol/sequences/Query.js:92:8)
    at Protocol._parsePacket (/home/esnesi/unreal/_NUTStats2/node_modules/mysql/                                                                                                                                                             lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/esnesi/unreal/_NUTStats2/node_modules/mysql/li                                                                                                                                                             b/protocol/Parser.js:433:10)
    at Parser.write (/home/esnesi/unreal/_NUTStats2/node_modules/mysql/lib/proto                                                                                                                                                             col/Parser.js:43:10)
    at Protocol.write (/home/esnesi/unreal/_NUTStats2/node_modules/mysql/lib/pro                                                                                                                                                             tocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/esnesi/unreal/_NUTStats2/node_modules/mysql/lib                                                                                                                                                             /Connection.js:88:28)
/home/esnesi/unreal/_NUTStats2/node_modules/mysql/lib/protocol/Parser.js:437
      throw err; // Rethrow non-MySQL errors

**Comment by esnesi** [comment]
Ok above seemed to be from my side still.
Created new build, imported quite some logs, but halted at a DOM log:

[17:50:17] Notice: Gametype is Domination
[17:50:17] Notice: A gametype with that name does not have an id yet, creating one now.
[17:50:17] Notice: Gametype Domination has been inserted to database with the id of 3
[17:50:17] Pass: Inserted gametype info into database.
[17:50:17] Notice: Gametype is Domination
Trace: TypeError: Cannot read property 'stats' of null
    at PlayerManager.setKills (/home/esnesi/unreal/_NUTStats2/api/importer/playermanager.js:547:31)
    at MatchManager.import (/home/esnesi/unreal/_NUTStats2/api/importer/matchmanager.js:80:32)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Importer.importLogs (/home/esnesi/unreal/_NUTStats2/api/importer/importer.js:74:37)
    at async MyEmitter.<anonymous> (/home/esnesi/unreal/_NUTStats2/api/importer/importer.js:119:17)
    at MatchManager.import (/home/esnesi/unreal/_NUTStats2/api/importer/matchmanager.js:317:21)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Importer.importLogs (/home/esnesi/unreal/_NUTStats2/api/importer/importer.js:74:37)
    at async MyEmitter.<anonymous> (/home/esnesi/unreal/_NUTStats2/api/importer/importer.js:119:17)
Trace: TypeError: Cannot read property 'updatedPlayers' of undefined
    at Importer.updateCurrentUpdatedStats (/home/esnesi/unreal/_NUTStats2/api/importer/importer.js:51:48)
    at Importer.importLogs (/home/esnesi/unreal/_NUTStats2/api/importer/importer.js:78:22)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async MyEmitter.<anonymous> (/home/esnesi/unreal/_NUTStats2/api/importer/importer.js:119:17)
    at Importer.importLogs (/home/esnesi/unreal/_NUTStats2/api/importer/importer.js:108:21)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async MyEmitter.<anonymous> (/home/esnesi/unreal/_NUTStats2/api/importer/importer.js:119:17)

**Comment by scottadkin** [comment]
Fixed the ping and ctf crashes

**Comment by esnesi** [comment]
Seems better now, like a magicpotato!
It's importing 15k logs now.
Thanks!

**Comment by esnesi** [comment]
yeah halts at this now it seems

[18:56:59] Notice: Gametype is Capture the Flag
[18:56:59] Pass: Inserted gametype info into database.
[18:56:59] Notice: Gametype is Capture the Flag
[18:56:59] Pass: Inserted server info into database.
[18:56:59] Notice: There is no spawn data from map with id 96, creating now.
[18:57:00] Pass: Inserted map info into database.
[18:57:00] Pass: Inserted match info into database.
[18:57:00] Notice: Found 15 Capture The Flag Data to parse
Trace: TypeError: Cannot read property 'push' of undefined
    at CTFManager.createCapData (/home/esnesi/unreal/_NUTStats2/api/importer/ctfmanager.js:233:37)
    at CTFManager.parseData (/home/esnesi/unreal/_NUTStats2/api/importer/ctfmanager.js:155:14)
    at MatchManager.import (/home/esnesi/unreal/_NUTStats2/api/importer/matchmanager.js:117:37)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Importer.importLogs (/home/esnesi/unreal/_NUTStats2/api/importer/importer.js:74:37)
    at async MyEmitter.<anonymous> (/home/esnesi/unreal/_NUTStats2/api/importer/importer.js:119:17)
    at MatchManager.import (/home/esnesi/unreal/_NUTStats2/api/importer/matchmanager.js:317:21)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Importer.importLogs (/home/esnesi/unreal/_NUTStats2/api/importer/importer.js:74:37)
    at async MyEmitter.<anonymous> (/home/esnesi/unreal/_NUTStats2/api/importer/importer.js:119:17)
Trace: TypeError: Cannot read property 'updatedPlayers' of undefined
    at Importer.updateCurrentUpdatedStats (/home/esnesi/unreal/_NUTStats2/api/importer/importer.js:51:48)
    at Importer.importLogs (/home/esnesi/unreal/_NUTStats2/api/importer/importer.js:78:22)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async MyEmitter.<anonymous> (/home/esnesi/unreal/_NUTStats2/api/importer/importer.js:119:17)
    at Importer.importLogs (/home/esnesi/unreal/_NUTStats2/api/importer/importer.js:108:21)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async MyEmitter.<anonymous> (/home/esnesi/unreal/_NUTStats2/api/importer/importer.js:119:17)

**Comment by scottadkin** [comment]
I don't know if you got the real latest build or not, I pushed 2 commits within a few minutes of each other because I made a small mistake. Also added some more fixes for ctf matches.

**Comment by esnesi** [comment]
It goes better.
Seems to have a new thing now.

[20:35:21] Progress: Starting import of log number 21 of 64
[20:35:21] Notice: Starting import of log file Unreal.ngLog.2021.08.31.16.21.14.5555.log
[20:35:21] Notice: Log file id is 315
[20:35:21] Notice: Gametype is Tournament DeathMatch
[20:35:21] Pass: Inserted gametype info into database.
[20:35:21] Notice: Gametype is Tournament DeathMatch
[20:35:21] Pass: Inserted server info into database.
Trace: Error: ER_DATA_TOO_LONG: Data too long for column 'level_enter_text' at row 1
    at Query.Sequence._packetToError (/home/esnesi/unreal/_NUTStats2/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/home/esnesi/unreal/_NUTStats2/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/home/esnesi/unreal/_NUTStats2/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/esnesi/unreal/_NUTStats2/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/esnesi/unreal/_NUTStats2/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/esnesi/unreal/_NUTStats2/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/esnesi/unreal/_NUTStats2/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/home/esnesi/unreal/_NUTStats2/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:290:12)
    --------------------
    at Pool.query (/home/esnesi/unreal/_NUTStats2/node_modules/mysql/lib/Pool.js:199:23)
    at /home/esnesi/unreal/_NUTStats2/api/maps.js:43:19
    at tryCallTwo (/home/esnesi/unreal/_NUTStats2/node_modules/promise/lib/core.js:45:5)
    at doResolve (/home/esnesi/unreal/_NUTStats2/node_modules/promise/lib/core.js:200:13)
    at new Promise (/home/esnesi/unreal/_NUTStats2/node_modules/promise/lib/core.js:66:3)
    at Maps.insert (/home/esnesi/unreal/_NUTStats2/api/maps.js:39:16)
    at Maps.updateStats (/home/esnesi/unreal/_NUTStats2/api/maps.js:146:28)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async MapInfo.updateStats (/home/esnesi/unreal/_NUTStats2/api/importer/mapInfo.js:63:13) {
  code: 'ER_DATA_TOO_LONG',
  errno: 1406,
  sqlMessage: "Data too long for column 'level_enter_text' at row 1",
  sqlState: '22001',
  index: 0,
  sql: "INSERT INTO nstats_maps VALUES(NULL,'DM-!XC-EpicTownV2A','DM-XC-EpicTown-V2A','Rob -=FraGnBraG=- Burns','16-24','Built for UT99.org Xmas 2012 contest :)  ***DISCLAIMER*** This map merges together UT99 game content in a fun Tribute to the developers of UT. EpicTown was created with no collaboration with or endorsement by Epic Games or any of their former of current employees or contractors. Any custom textures or modified versions of UT product textures that are presented in Epic Town as corporate logos are entirely ficticious work and are not meant to represent any real companies. Rob Burns :)',1630426874,1630426874,1,25.520000000000437)"
}

**Comment by esnesi** [comment]
Got a weird pagecount as well it seems:
https://stats2.xjon.me/matches

**Comment by esnesi** [comment]
and another FYI
![image](https://user-images.githubusercontent.com/58574380/133942482-d8977659-ebb7-44ca-8b98-232ccf79f1a4.png)

**Comment by esnesi** [comment]
The dates on the matches arn't right.
It does show recent matches, but it does show alot of matches on that page which are years ago  as well.

Was there also an option to hide botmatches like in the older build ?

**Comment by esnesi** [comment]
another FYI
![image](https://user-images.githubusercontent.com/58574380/133942666-1d700a11-1352-490d-b5a7-2b8cb081a8f9.png)
should be "npm run build"

**Comment by esnesi** [comment]
*Continued on discord
