### ISSUE TITLE
2.10.2 update error

### ISSUE THREAD

**Issue by c0br3tii** [scottadkin/node-utstats-2#25]
while running sudo node install
ubuntu@pi42:~/utstat2_new$ sudo node install
[17:20:40] Pass: Performed query 1 of 295
[17:20:40] Pass: Performed query 2 of 295
[17:20:40] Pass: Performed query 3 of 295
[17:20:40] Pass: Performed query 4 of 295
[17:20:40] Pass: Performed query 5 of 295
[17:20:40] Pass: Performed query 6 of 295
[17:20:40] Pass: Performed query 7 of 295
[17:20:40] Pass: Performed query 8 of 295
[17:20:40] Pass: Performed query 9 of 295
[17:20:40] Pass: Performed query 10 of 295
[17:20:40] Pass: Performed query 11 of 295
[17:20:40] Pass: Performed query 12 of 295
Trace: Error: ER_TABLE_EXISTS_ERROR: Table 'nstats_ctf_flag_drops' already exists
    at Sequence._packetToError (/home/ubuntu/utstat2_new/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/home/ubuntu/utstat2_new/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/home/ubuntu/utstat2_new/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/ubuntu/utstat2_new/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/ubuntu/utstat2_new/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/ubuntu/utstat2_new/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/ubuntu/utstat2_new/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/home/ubuntu/utstat2_new/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    --------------------
    at Pool.query (/home/ubuntu/utstat2_new/node_modules/mysql/lib/Pool.js:199:23)
    at /home/ubuntu/utstat2_new/install.js:1697:19
    at new Promise (<anonymous>)
    at basicQuery (/home/ubuntu/utstat2_new/install.js:1695:16)
    at /home/ubuntu/utstat2_new/install.js:1711:19
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ER_TABLE_EXISTS_ERROR',
  errno: 1050,
  sqlMessage: "Table 'nstats_ctf_flag_drops' already exists",
  sqlState: '42S01',
  index: 0,
  sql: 'CREATE TABLE nstats_ctf_flag_drops (\n' +
    '        id int NOT NULL AUTO_INCREMENT,\n' +
    '        match_id int NOT NULL,\n' +
    '        match_date int NOT NULL,\n' +
    '        map_id int NOT NULL,\n' +
    '        timestamp float NOT NULL,\n' +
    '        cap_id int NOT NULL,\n' +
    '        flag_team int NOT NULL,\n' +
    '        player_id int NOT NULL,\n' +
    '        player_team int NOT NULL,\n' +
    '        distance_to_cap float NOT NULL,\n' +
    '        position_x float NOT NULL,\n' +
    '        position_y float NOT NULL,\n' +
    '        position_z float NOT NULL,\n' +
    '        time_dropped float NOT NULL,\n' +
    '        PRIMARY KEY(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;'
}
    at /home/ubuntu/utstat2_new/install.js:1738:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by c0br3tii** [comment]
one other thing, how do we restore a previous backed up database? thanks

**Comment by scottadkin** [comment]
If you want permalinks for every match you would need to reimport. The restore tool hasn't been tested much and can only be used via command line, I just tested it however and it doesn't work atm.

**Comment by scottadkin** [comment]
Ok turns out I was being stupid and forgot a step, after you create a backup you need to copy all the files from inside the .zip file and place them into the **restore-from** folder, then run **node testrestore** in the main directory, I forgot the latter and that's why it was spitting out loads of mysql errors as the backup was from an old version.

Also note you can only restore the backup to the same version it was from, you can not restore for example v2.9.x to v.2.10.0, I've not got round to making the admin UI for restoring, and to be honest was surprised that it still works.
